name: CI

on:
  push:
    branches:
      - '*'  # Runs on commits to any branch
  pull_request:
    branches:
      - '*'  # Runs on pull requests targeting any branch

jobs:
  benchmarks:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ 3.1, 3.2, 3.3 ]

    steps:
      - uses: actions/checkout@master

      - name: Sets up the Ruby version
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Sets up the environment
        run: |
          gem install -q bundler
          bundle install

      - name: Runs the benchmarks
        run: benchmark-driver ./all.yml --bundler
